ToDoList/urls.py
from django.urls import path
from ToDoList.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    
    #Authentication-URLS
    path('',LoginView.as_view(),name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('error/',ErrorView.as_view(),name="error"),
    path('change_password/',ChangePasswordView.as_view(),name='change_password'),
    
    
    #Main-URLS
    path('home/',Dashboard.as_view(),name="home"),
    path('Profile/',ProfilePageView.as_view(),name="profile"),
    
    
    #User-URLS
    path('add_user/',UserView_Add.as_view(),name="add_user"),
    path('update_user/<int:id>', UserView_Update.as_view(), name="update"),
    path('user_list/',UserView_List.as_view(),name="userlist"),
    path('delete/<int:id>',UserView_Delete.as_view(),name='delete'),
    
    
    #Todos-URLS
    path('add_todo/',TodoView_Add.as_view(),name="add_todo"),
    path('todo_list/',TodoView_List.as_view(),name="todolist"),
    path('update_comment/<int:id>', TodoComment.as_view(), name="updatecomment"),
    
    
    #Todos-Others-URLS
    path('todo/<int:todo_id>/notes/', NoteHistoryView.as_view(), name='note_history'),
    path('update_todo_status/<int:todo_id>/',TodoView_Update.as_view(), name='update_todo_status'),
    path('update_todo_start_time/<int:todo_id>/', TodoView_StartTime.as_view(), name='update_todo_start_time'),
    
    
    #Notifications-URLS
    path('notifications/', NotificationListView.as_view(), name='notifications'),
   
   
    #Notifications-URLS-FunctionBased
    path('notifications/mark_all_as_read/', mark_all_as_read, name='mark_all_as_read'),
    path('mark-as-read/<int:notification_id>/', mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications/clear_all/', clear_all_notifications, name='clear_all_notifications'),
   
    
    #Team-URLS
    path('teamtodo/',TeamTodoView.as_view(),name="teamtodo"),
    path('team/',TeamView.as_view(),name="team"),
    
    
    #Others-URLS
    path('system_settings/',SettingsView.as_view(),name="system_settings"),
    path('user/<int:user_id>/task/<int:task_id>/', TaskDetailView.as_view(), name='task_detail'),
    path('users/toggle/<int:user_id>/', ToggleActiveStatusView.as_view(), name='toggle_active_status'),
    
 
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from ToDoList.views import *
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ToDoList.urls")),
 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ToDoList/models.py
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Team(models.Model):
    team_department = models.CharField(max_length=100)

    def __str__(self):
        return self.team_department

class CustomUserManager(BaseUserManager):
    def create_user(self, user_name, email, mobile_number, role, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        if not user_name:
            raise ValueError('The User Name field must be set')
        if not mobile_number:
            raise ValueError('The Mobile Number field must be set')
        if role is None:
            raise ValueError('The Role field must be set')

        email = self.normalize_email(email)
        user = self.model(
            user_name=user_name,
            email=email,
            mobile_number=mobile_number,
            role=role,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_name, email, mobile_number, role, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(user_name, email, mobile_number, role, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    USER = (
        ('1', 'Admin'),
        ('2', 'TeamLeader'),
        ('3', 'Developer'),
    )

    user_name = models.CharField(_("user name"), max_length=150, unique=True)
    email = models.EmailField(_("email address"), unique=True)
    mobile_number = models.CharField(_("mobile number"), max_length=15, unique=True)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True, related_name="members")
    role = models.CharField(max_length=50, choices=USER, default='3')
    photo = models.ImageField(_("photo"), upload_to="user_photos/", blank=True, null=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "user_name"
    REQUIRED_FIELDS = ["email", "mobile_number", "role"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def toggle_active_status(self):
        self.is_active = not self.is_active
        self.save()
    def get_full_name(self):
        """Return the full name of the user."""
        return self.user_name

    def get_short_name(self):
        """Return the short name of the user."""
        return self.user_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)
    

class Todo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.IntegerField(default=0)
    date_created = models.DateTimeField(default=timezone.now)
    start_time = models.DateTimeField(null=True, blank=True)
    update_time = models.DateTimeField(null=True, blank=True)
    note = models.TextField(blank=True, null=True)
    updated_by=models.CharField(max_length=20,blank=True, null=True)
 



    def __str__(self):
        return self.title


class Notification(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_notifications', on_delete=models.CASCADE)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_notifications', on_delete=models.CASCADE)
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Notification from {self.sender} to {self.receiver} about {self.todo}'

    @property
    def display_message(self):
        return f"{self.message} ✓✓" if self.is_read else self.message

class Notes(models.Model):
    todo = models.ForeignKey(Todo, related_name='notes', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    updated_by=models.CharField(max_length=20,blank=True, null=True)
    
    def __str__(self):
        return self.description



class SystemSettings(models.Model):
    id = models.AutoField(primary_key=True)
    company_name = models.CharField(max_length=50)
    company_logo = models.TextField()
    location=models.CharField(max_length=200)
    company_info=models.TextField()
    small_logo = models.TextField(blank=True, null=True)  # New field for small logo
    mobile = models.CharField(_("mobile number"), max_length=15, unique=True)
    email = models.CharField(max_length=30)
    facebook = models.CharField(max_length=70)
    instagram = models.CharField(max_length=70)
    linkdein = models.CharField(max_length=70)
    company_link = models.CharField(max_length=70)
    

templates/admin_templates/add_todo.html
{% extends "layouts/base_auth.html" %} 
{% block content %} 
{% include "includes/sidebar.html" %}
{% include "includes/navigation.html" %} 
<section class="pcoded-main-container">
    <div class="pcoded-wrapper">
        <div class="pcoded-content">
            <div class="pcoded-inner-content">
                <!-- [ breadcrumb ] start -->
                <div class="page-header">
                    <div class="page-block">
                        <div class="row align-items-center">
                            <div class="col-md-12">
                                <div class="page-header-title">
                                    <h5 class="m-b-10"></h5>
                                </div>
                                
                               
                            </div>
                        </div>
                    </div>
                </div>
                <!-- [ breadcrumb ] end -->
                <div class="main-body">
                    <div class="page-wrapper">
                        <!-- [ Main Content ] start -->
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>Add Todo</h5>
                                    </div>
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <form method="post" novalidate> 
                                                    {% csrf_token %}
                                                    <div class="form-group mb-3">
                                                        <label for="id_username">Username</label>
                                                        <div class="input-group mb-3">
                                                            <input type="text"  class="form-control" value="{{ user}}" readonly >
                                                            <input type="text" id="user" name="user" class="form-control" value="{{ user.id }}" readonly hidden>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="id_title">Title</label>
                                                        <div class="input-group mb-3">
                                                            {{ form.title }}
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="id_description">Description</label>
                                                        <div class="input-group mb-3">
                                                            {{ form.description }}
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-3">
                                                      <label for="id_status">Status</label>
                                                      <div class="input-group mb-3">
                                                          <input type="text" id="id_status" name="status" value="0" class="form-control" readonly hidden>
                                                          <input type="text" id="team" name="team" value="{{ user.team.id }}" class="form-control" readonly hidden>
                                                          <input type="text"  value="pending" class="form-control" readonly>
                                                      </div>
                                                    </div>
                                                    <div class="form-group mb-3">
                                                        <label for="id_date_created">Date Created</label>
                                                        <div class="input-group mb-3">
                                                            <input type="datetime-local" id="id_date_created" name="date_created" class="form-control">
                                                        </div>
                                                    </div>
                                                  
                                                    <button class="btn btn-primary shadow-2">Submit</button>
                                                </form>
                                            </div>
                                            <div class="col-md-6"></div>
                                        </div>
                                        <!-- [ Main Content ] end -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- [ Main Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 
{% include "includes/footer.html" %} 

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Get the current date and time in UTC
        var now = new Date();
        
        // Convert to Indian Standard Time (IST), which is UTC+5:30
        var istOffset = 5.5 * 60 * 60 * 1000; // IST offset in milliseconds
        var istDate = new Date(now.getTime() + istOffset);
        
        // Format the date to 'YYYY-MM-DDTHH:MM'
        var date = istDate.toISOString().slice(0, 16);
        
        // Set the value of the input field
        document.getElementById('id_date_created').value = date;
    });
</script>
{% endblock content %}

templates/admin_templates/admintodolist.html
{% extends 'layouts/base_auth.html' %}
{% block content %}
{% include "includes/sidebar.html" %}
{% include "includes/navigation.html" %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
    <section class="pcoded-main-container">
        <div class="pcoded-wrapper">
            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <h1>Todo List</h1>
                    {% for team, todos in team_todos.items %}
                    <h2>{{ team }} </h2>

                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Username</th>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Date Created</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for todo in todos %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ todo.user }}</td>
                                    <td>{{ todo.title }}</td>
                                    <td>{{ todo.description }}</td>
                                    <td>{{ todo.date_created|date:"d-M-Y" }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% include "includes/footer.html" %} 

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        $(document).ready(function() {
            $('#todoTable').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
                "order": [[5, "desc"]],  // Default order by date_created column
            });
        });
    </script>

{% endblock content %}

templates/admin_templates/change_password.html
{% extends "layouts/base_auth.html" %}
{% load widget_tweaks %}

{% block content %}
  {% include "includes/sidebar.html" %}
  {% include "includes/navigation.html" %}

  <section class="pcoded-main-container">
    <div class="pcoded-wrapper">
      <div class="pcoded-content">
        <div class="pcoded-inner-content">
          <div class="main-body">
            <div class="page-wrapper">
              <div class="row">
                <div class="col-sm-12">
                  <div class="card">
                    <div class="card-header">
                      <h5>Change Password</h5>
                    </div>
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-6">
                          <form method="post"  action="{% url 'change_password' %}" novalidate>
                            {% csrf_token %}

                            <div class="form-group">
                              <label for="id_old_password">Old Password</label>
                              {{ form.old_password|add_class:"form-control" }}
                              {% for error in form.old_password.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                              {% endfor %}
                            </div>

                            <div class="form-group">
                              <label for="id_new_password1">New Password</label>
                              {{ form.new_password1|add_class:"form-control" }}
                              {% for error in form.new_password1.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                              {% endfor %}
                            </div>

                            <div class="form-group">
                              <label for="id_new_password2">Confirm New Password</label>
                              {{ form.new_password2|add_class:"form-control" }}
                              {% for error in form.new_password2.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                              {% endfor %}
                            </div>

                            <button type="submit" class="btn btn-primary">Change Password</button>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  
  {% include "includes/messages.html" %}
  {% include "includes/footer.html" %} 
  
{% endblock content %}

templates/admin_templates/error.html
{% extends "layouts/base_error.html" %}
{% block content %}

    <header class="top-header">
  </header>
  
  <!--dust particel-->
  <div>
    <div class="starsec"></div>
    <div class="starthird"></div>
    <div class="starfourth"></div>
    <div class="starfifth"></div>
  </div>
  <!--Dust particle end--->
  
  
  <div class="lamp__wrap">
    <div class="lamp">
      <div class="cable"></div>
      <div class="cover"></div>
      <div class="in-cover">
        <div class="bulb"></div>
      </div>
      <div class="light"></div>
    </div>
  </div>
  <!-- END Lamp -->
  <section class="error">
    <!-- Content -->
    <div class="error__content">
      <div class="error__message message">
        <h1 class="message__title">Page Not Found</h1>
        <p class="message__text">We're sorry, The link you followed may either be broken or no longer exists if you are not login. Please try again.</p>
      </div>
      <div class="error__nav e-nav">
        <a href="{% url 'home' %}" target="_blanck" class="e-nav__link"></a>
      </div>
    </div>
    <!-- END Content -->
  
  </section>
  
    </a>
    <label class="d-none">
        <i class="icon feather icon-moon" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none" />
      </label>
{% endblock content %}

templates/admin_templates/forbiddenerror.html
{% extends "layouts/base_error.html" %}
{% block content %}

<a href="https://codepen.io/uiswarup/full/vYPxywO" target="_blank">
    <header class="top-header">
  </header>
  
  <!--dust particel-->
  <div>
    <div class="starsec"></div>
    <div class="starthird"></div>
    <div class="starfourth"></div>
    <div class="starfifth"></div>
  </div>
  <!--Dust particle end--->
  
  
  <div class="lamp__wrap">
    <div class="lamp">
      <div class="cable"></div>
      <div class="cover"></div>
      <div class="in-cover">
        <div class="bulb"></div>
      </div>
      <div class="light"></div>
    </div>
  </div>
  <!-- END Lamp -->
  <section class="error">
    <!-- Content -->
    <div class="error__content">
      <div class="error__message message">
        <h1 class="message__title">404! ERROR</h1>
        <p class="message__text">YOU ARE NOT AUTHORIZED FOR THIS DATA</p>
      </div>
      <div class="error__nav e-nav">
        <a href="{% url 'home' %}"  class="e-nav__link"></a>
      </div>
    </div>
    <!-- END Content -->
  
  </section>
  
    </a>
    <label class="d-none">
        <i class="icon feather icon-moon" id="theme-indicator"></i>
        <input type="checkbox" id="theme-switch" class="d-none" />
      </label>
{% endblock content %}

templates/admin_templates/user_list.html
{% extends "layouts/base_auth.html" %}
{% block content %}
{% include "includes/sidebar.html" %}
{% include "includes/navigation.html" %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<style>
  #id_user {
    border: 1px solid #ccc;
    padding: 8px;
    font-size: 14px;
    width: 200px;
  }

  #id_team {
    border: 1px solid #ccc;
    padding: 8px;
    font-size: 14px;
    width: 200px;
  }

  #datepicker {
    border: 1px solid #ccc;
    padding: 8px;
    font-size: 14px;
    width: 200px;
  }

  .todoTable {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
    font-size: 15px;
    text-align: left;
  }

  .todoTable thead th {
    background-color: #343a40;
    color: white;
    padding: 12px;
    cursor: pointer;
    position: relative;
  }

  .todoTable thead th.sorting:after,
  .todoTable thead th.sorting_asc:after,
  .todoTable thead th.sorting_desc:after {
    content: "";
    position: absolute;
    right: 10px;
    top: 50%;
    transform: translateY(-50%);
    border: 5px solid transparent;
  }

  .todoTable thead th.sorting:after {
    border-top-color: white;
  }

  .todoTable thead th.sorting_asc:after {
    border-bottom-color: white;
    transform: translateY(-50%) rotate(180deg);
  }

  .todoTable thead th.sorting_desc:after {
    border-top-color: white;
  }

  .todoTable tbody tr {
    border-bottom: 1px solid #dddddd;
  }

  .todoTable tbody tr:last-of-type {
    border-bottom: 2px solid #343a40;
  }

  .dataTables_wrapper .dataTables_paginate {
    display: flex;
    justify-content: flex-end;
    align-items: center;
    margin-top: 20px;
  }

  .dataTables_wrapper .dataTables_paginate .paginate_button {
    display: inline-block;
    padding: 6px 12px;
    margin: 0 2px;
    border: 1px solid #343a40;
    border-radius: 4px;
    background-color: white;
    color: #343a40;
    cursor: pointer;
  }

  .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
    background-color: #343a40;
    color: white;
  }

  .dataTables_wrapper .dataTables_paginate .paginate_button.current {
    background-color: #343a40;
    color: white;
  }

  .dataTables_wrapper .dataTables_paginate .paginate_button.previous,
  .dataTables_wrapper .dataTables_paginate .paginate_button.next {
    font-weight: bold;
    margin: 0 5px;
  }

  .dataTables_wrapper .dataTables_filter {
    float: right;
    text-align: right;
  }

  .dataTables_wrapper .dataTables_filter label {
    font-weight: bold;
  }

  .dataTables_wrapper .dataTables_filter input {
    margin-left: 0.5em;
    padding: 6px;
    border: 1px solid #dddddd;
    border-radius: 4px;
  }

  body.dark .flatpickr-calendar {
    background-color: #343a40;
    color: white;
  }

  body.dark .flatpickr-calendar .flatpickr-day {
    color: white;
  }

  body.dark .flatpickr-calendar .flatpickr-day:hover,
  body.dark .flatpickr-calendar .flatpickr-day:focus {
    background-color: #495057;
  }

  body.dark .flatpickr-calendar .flatpickr-day.today {
    background-color: #495057;
  }

  body.dark .flatpickr-calendar .flatpickr-day.selected {
    background-color: #007bff;
  }

  body.dark .flatpickr-calendar .flatpickr-months,
  .flatpickr-calendar .flatpickr-weekdays {
    background-color: #343a40;
  }

  body.dark .flatpickr-calendar .flatpickr-time input {
    background-color: #343a40;
    color: white;
  }
</style>

<section class="pcoded-main-container">
  <div class="pcoded-wrapper">
    <div class="pcoded-content">
      <div class="pcoded-inner-content">
        <div class="main-body">
          <div class="page-wrapper">
            <div class="row">
              <div class="col-xl-12">
                <div class="card">
                  <div class="card-header">
                    <h5>User List</h5>
                    <i class="fa-solid fa-table"></i>
                  </div>
                  <div class="card-block table-border-style">
                    <div class="table-responsive">
                      <table class="userTable table">
                        <thead>
                          <tr>
                            <th>id</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Team</th>
                            <th>Role</th>
                            <th>Active</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for i in users %}
                          <tr>
                            <th scope="row">{{i.id}}</th>
                            <td>{{i.user_name}}</td>
                            <td>{{i.email}}</td>
                            <td>{{i.mobile_number}}</td>
                            <td>{{i.team}}</td>
                            <td>{{i.get_role_display}}</td>
                            <td>
                              <form method="post" action="{% url 'toggle_active_status' i.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link">
                                  {% if i.is_active %}
                                    Active
                                  {% else %}
                                    Deactivate
                                  {% endif %}
                                </button>
                              </form>
                            </td>
                            <td>
                              <a href="{% url 'update' i.id %}">
                                <i class="fa-solid fa-user-pen text-c-green"></i>
                              </a>
                              &nbsp;&nbsp;
                              <a href="javascript:void(0);" onclick="confirmDelete('{{i.id}}');">
                                <i class="fa-solid fa-user-xmark text-c-green"></i>
                              </a>
                              <form id="delete-form-{{i.id}}" method="get" action="{% url 'delete' i.id %}" style="display: none;">
                                {% csrf_token %}
                              </form>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <label class="d-none">
              <i class="icon feather icon-moon" id="theme-indicator"></i>
              <input type="checkbox" id="theme-switch" class="d-none" />
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% include "includes/footer.html" %} 

<label class="d-none">
  <i class="icon feather icon-moon" id="theme-indicator"></i>
  <input type="checkbox" id="theme-switch" class="d-none" />
</label>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script>
  $(document).ready(function() {
    $(".userTable").DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "info": true,
      "autoWidth": true,
      "responsive": true,
      "order": [
        [0, "asc"]
      ],
      "lengthMenu": [5, 10, 25, 50]
    });
  });

  function confirmDelete(userId) {
    Swal.fire({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
      if (result.isConfirmed) {
        document.getElementById('delete-form-' + userId).submit();
      }
    });
  }
</script>

{% endblock content %}